version: "3.8"

services:
  app:
    container_name: brain_app
    build: .
    restart: "always"
    volumes:
      - "./test_model/:/usr/src/models/test_model"
    ports:
      - 8501:8501
    environment:
      - MODEL_NAME=test_model
      - MODEL_BASE_PATH=/usr/src/models
      - PORT=8501
