version: "3.8"

services:
  app:
    container_name: brain_app
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: "always"
    volumes:
      - "./brain_tumor_detection/:/models/brain_tumor_detection"
    ports:
      - 8501:8501
    environment:
      - MODEL_NAME=brain_tumor_detection
      - MODEL_BASE_PATH=/models
      - PORT=8501
